# Generated by Django 4.0 on 2021-12-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_foods", "0004_rename_ispremium_food_is_premium_and_more"),
        ("app_general", "0003_subscription_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_foods.food",
            ),
        ),
    ]
