# Generated by Django 4.0 on 2021-12-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_foods", "0002_alter_food_ispremium_alter_food_promotionendat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="food",
            name="specialPrice",
            field=models.IntegerField(null=True),
        ),
    ]
